Eko 0.13
NNPDF/yadism pull request #194
Opened 2023-05-23 14:59 UTC by giacomomagni

Update eko dependency to`^0.13.1`

2023-05-23 15:46 UTC, giacomomagni commented
Tests are passing for me locally,  I was not able to fix the issue on the workflow...
But the PR should be ready for review.

2023-05-23 21:59 UTC, AleCandido commented
The issue in the workflows is the one described here:
https://github.com/NNPDF/yadism/pull/193#issuecomment-1560150804

You should just fix the Poetry groups in the same fashion of those in EKO and Pineko.
If you do it, and rerun `poetry update`, we could even close #193, as superseded by this.

2023-05-24 09:48 UTC, felixhekhorn requested changes

2023-05-24 09:48 UTC, felixhekhorn commented on src/yadism/output.py
> +            origin=(theory["Q0"] ** 2, theory["nf0"]),
```suggestion
            origin=(theory["Qref"] ** 2, theory["nfref"]),
```
this is for $\alpha_s$

2023-05-24 09:48 UTC, felixhekhorn commented on src/yadmark/benchmark/runner.py
> +                origin=(theory["Q0"] ** 2, theory["nf0"]),
```suggestion
                origin=(theory["Qref"] ** 2, theory["nfref"]),
```
as before

2023-05-24 10:19 UTC, AleCandido approved these changes

2023-05-24 12:17 UTC, merged